- name: Ensure the default php-fpm conf exists.
  template:
    src: "{{ role_path }}/templates/php-fpm.conf.j2"
    dest: "{{ php_conf_paths }}/php-fpm.conf"
    owner: root
    group: root
    mode: 0644

- name: Ensure the default pool directory exists.
  file:
    path: "{{ php_fpm_pool_conf_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure the default pool exists.
  template:
    src: "{{ role_path }}/templates/pool.d/www.conf.j2"
    dest: "{{ php_fpm_pool_conf_path }}/www.conf"
    owner: root
    group: root
    mode: 0644

- name: Configure php-fpm pool (if enabled).
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^user.?=.+$"
      line: "user = {{ php_fpm_pool_user }}"
    - regexp: "^group.?=.+$"
      line: "group = {{ php_fpm_pool_group }}"
    - regexp: "^listen.?=.+$"
      line: "listen = {{ php_fpm_listen }}"
    - regexp: '^listen\.allowed_clients.?=.+$'
      line: "listen.allowed_clients = {{ php_fpm_listen_allowed_clients }}"
    - regexp: '^pm\.max_children.?=.+$'
      line: "pm.max_children = {{ php_fpm_pm_max_children }}"
    - regexp: '^pm\.start_servers.?=.+$'
      line: "pm.start_servers = {{ php_fpm_pm_start_servers }}"
    - regexp: '^pm\.min_spare_servers.?=.+$'
      line: "pm.min_spare_servers = {{ php_fpm_pm_min_spare_servers }}"
    - regexp: '^pm\.max_spare_servers.?=.+$'
      line: "pm.max_spare_servers = {{ php_fpm_pm_max_spare_servers }}"

