- name: Ensure dependencies for building from source are installed (RedHat).
  yum: "pkg={{ item }} state=installed"
  with_items:
    - autoconf
    - automake
    - libtool
    - bison
    - make
    - curl-devel
    - recode-devel
    - aspell-devel
    - libxml2-devel
    - pkgconfig
    - libmcrypt-devel
    - t1lib-devel
    - libXpm-devel
    - libpng-devel
    - libjpeg-turbo-devel
    - bzip2-devel
    - openssl-devel
    - freetype-devel
    - libicu-devel
    - mariadb-devel
    - gmp-devel
  when: ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure dependencies for building from source are installed (Debian).
  apt: "pkg={{ item }} state=installed"
  with_items:
    - build-essential
    - autoconf
    - automake
    - libtool
    - bison
    - pkg-config
    - re2c
    - libxml2-dev
    - libcurl4-openssl-dev
    - libbz2-dev
    - libjpeg-dev
    - libpng12-dev
    - libxpm-dev
    - libfreetype6-dev
    - libgmp3-dev
    - libmcrypt-dev
    - libmysqlclient-dev
    - libpspell-dev
    - librecode-dev
    - libssl-dev
  when: ansible_os_family == 'Debian'


# Requirements
- name: Make sure we can clone PHP repository using git.
  apt: name=git state=present
